services:
  mysql:
    image: mysql:8.0.38
    container_name: mysql2
    environment:
      - MYSQL_DATABASE = mamdaero
      - MYSQL_ROOT_HOST = %
      - MYSQL_ROOT_PASSWORD = root
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/mysql:/var/lib/mysql
    networks:
      - internal_network


  spring:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    container_name: spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mamdaero?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    networks:
      - internal_network
networks:
  internal_network: