spring:
  application:
    name: mamdaero

  config:
    import: application-secret.yml

# LiveKit configuration
livekit:
  api:
    key: ${LIVEKIT_API_KEY:devkey}
    secret: ${LIVEKIT_API_SECRET:secret}

